using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;


namespace WebviewBind;

/// <summary>
/// Generates WebView2 message-dispatch infrastructure for partial classes marked with [WebviewContainer].
/// Methods marked with [WebviewExport] are automatically registered as endpoints callable from JavaScript.
/// </summary>
[Generator]
public class WebviewExportGenerator : IIncrementalGenerator
{
    private const string ContainerAttributeFullName = "WebviewBind.WebviewContainerAttribute";
    private const string ExportAttributeFullName = "WebviewBind.WebviewExportAttribute";

    // Injected attribute definitions added to the compilation
    private const string AttributesSource = @"// <auto-generated/>

namespace WebviewBind
{
    /// <summary>
    /// Marks a partial class as a WebView2 container.
    /// The source generator emits message-dispatch infrastructure in the generated partial part.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public sealed class WebviewContainerAttribute : System.Attribute { }

    /// <summary>
    /// Marks a method as callable from JavaScript via InvokeHostMethod().
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public sealed class WebviewExportAttribute : System.Attribute { }
}";

    // Injected helper type added to the compilation
    private const string HelperTypesSource = @"// <auto-generated/>
#nullable enable

namespace WebviewBind
{
    /// <summary>Call message format sent from JavaScript.</summary>
    internal sealed class WebviewCallMessage
    {
        [System.Text.Json.Serialization.JsonPropertyName(""callId"")]
        public string? CallId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName(""method"")]
        public string? Method { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName(""args"")]
        public System.Text.Json.JsonElement[]? Args { get; set; }
    }
}";

    /// <summary>
    /// Initializes the source generator by registering syntax providers and source output.
    /// The generator looks for classes annotated with [WebviewContainer] and generates WebView2 message
    /// handling code that allows JavaScript to call C# methods marked with [WebviewExport].
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register attribute definitions and helper types
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("WebviewAttributes.g.cs", SourceText.From(AttributesSource, Encoding.UTF8));
            ctx.AddSource("WebviewHelperTypes.g.cs", SourceText.From(HelperTypesSource, Encoding.UTF8));
        });

        // Filter classes annotated with [WebviewContainer]
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => GetClassDeclaration(ctx))
            .Where(t => t.found)
            .Select((t, _) => t.syntax);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(provider.Collect()),
            (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }

    private static (ClassDeclarationSyntax syntax, bool found) GetClassDeclaration(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        foreach (var attrList in classDecl.AttributeLists)
        foreach (var attr in attrList.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attr).Symbol is not IMethodSymbol attrSymbol)
                continue;
            if (attrSymbol.ContainingType.ToDisplayString() == ContainerAttributeFullName)
                return (classDecl, true);
        }
        return (classDecl, false);
    }

    private void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classDeclarations)
    {
        foreach (var classDecl in classDeclarations)
        {
            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classDecl.Identifier.Text;

            // Collect all methods annotated with [WebviewExport]
            var exportedMethods = classSymbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary
                    && m.GetAttributes().Any(a =>
                        a.AttributeClass?.ToDisplayString() == ExportAttributeFullName))
                .ToList();

            var switchCases = BuildSwitchCases(exportedMethods);
            var code = BuildPartialClass(namespaceName, className, switchCases);
            context.AddSource($"{className}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }

    /// <summary>
    /// Generates one switch case per exported method, handling argument deserialization and invocation (including async methods).
    /// </summary>
    private static string BuildSwitchCases(List<IMethodSymbol> methods)
    {
        var sb = new StringBuilder();
        foreach (var method in methods)
        {
            sb.AppendLine($"                case \"{method.Name}\":");

            // Build deserialization expressions for each parameter
            var argExprs = new List<string>();
            for (int i = 0; i < method.Parameters.Length; i++)
            {
                var paramType = method.Parameters[i].Type.ToDisplayString();
                argExprs.Add(
                    $"System.Text.Json.JsonSerializer.Deserialize<{paramType}>(call.Args![{i}].GetRawText())!");
            }
            var argList = string.Join(", ", argExprs);

            // Determine return shape: void / Task / Task<T> / plain value
            bool isVoid = method.ReturnsVoid;
            bool isTaskVoid = !isVoid
                && method.ReturnType.ToDisplayString() == "System.Threading.Tasks.Task";
            bool isTaskResult = !isVoid && !isTaskVoid
                && method.ReturnType is INamedTypeSymbol nt
                && nt.OriginalDefinition.ToDisplayString() == "System.Threading.Tasks.Task<TResult>";
            bool isAsync = isTaskVoid || isTaskResult;
            bool returnsValue = !isVoid && !isTaskVoid; // Includes Task<T> and plain return values

            string call = $"{method.Name}({argList})";
            if (isAsync && returnsValue)
                sb.AppendLine($"                    result = await {call};");
            else if (isAsync)
                sb.AppendLine($"                    await {call};");
            else if (returnsValue)
                sb.AppendLine($"                    result = {call};");
            else
                sb.AppendLine($"                    {call};");

            sb.AppendLine("                    break;");
        }
        return sb.ToString();
    }

    private static string BuildPartialClass(string namespaceName, string className, string switchCases)
    {
        return $@"// <auto-generated/>
#nullable enable

namespace {namespaceName};

partial class {className}
{{
    /// <summary>
    /// Registers the WebView2 message handler on CoreWebView2 so JavaScript can call
    /// C# methods marked with <c>[WebviewExport]</c> via
    /// <c>InvokeHostMethod(methodName, ...args)</c>.
    /// Call this method after <c>EnsureCoreWebView2Async</c> completes.
    /// </summary>
    public void RegisterWebviewHandler(Microsoft.Web.WebView2.Core.CoreWebView2 coreWebView2)
    {{
        coreWebView2.WebMessageReceived += OnWebviewMessageReceived;
    }}

    private async void OnWebviewMessageReceived(
        object? sender,
        Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs e)
    {{
        var raw = e.TryGetWebMessageAsString();
        if (string.IsNullOrEmpty(raw)) return;

        WebviewBind.WebviewCallMessage? call;
        try
        {{
            call = System.Text.Json.JsonSerializer.Deserialize<WebviewBind.WebviewCallMessage>(raw);
        }}
        catch
        {{
            return; // Ignore messages that are not in call format
        }}

        if (call?.CallId == null || call.Method == null) return;

        #if DEBUG
        Console.WriteLine($""Received call: {{call.Method}} (ID: {{call.CallId}})"");
        #endif

        await DispatchWebviewCall((Microsoft.Web.WebView2.Core.CoreWebView2)sender!, call);
    }}

    private async System.Threading.Tasks.Task DispatchWebviewCall(
        Microsoft.Web.WebView2.Core.CoreWebView2 coreWebView2,
        WebviewBind.WebviewCallMessage call)
    {{
        object? result = null;
        string? error = null;
        try
        {{
            switch (call.Method)
            {{
{switchCases}                default:
                    throw new System.InvalidOperationException(
                        $""Unknown exported method: {{call.Method}}"");
            }}
        }}
        catch (System.Exception ex)
        {{
            error = ex.Message;
        }}

        var response = System.Text.Json.JsonSerializer.Serialize(new
        {{
            callId = call.CallId,
            result,
            error,
        }});
        coreWebView2.PostWebMessageAsString(response);
    }}
}}
";
    }
}